# Generated by Django 2.2.6 on 2019-10-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduledEventID', models.IntegerField()),
                ('scheduledDate', models.CharField(max_length=200)),
                ('eventName', models.CharField(max_length=200)),
                ('startTime', models.CharField(max_length=200)),
                ('endTime', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
