# Generated by Django 2.2.6 on 2019-10-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191008_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scheduledDate',
            field=models.DateField(max_length=200),
        ),
    ]
