# Generated by Django 2.2.6 on 2019-10-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20191008_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduledDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
