# Generated by Django 2.2.6 on 2019-10-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20191008_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='scheduledEventID',
        ),
    ]
